### Write a NumPy program to test whether none of the elements of a given array is zero.

In [13]:
import numpy as np
def chechzeroelement():
    Rows = int(input("Give the number of rows:"))  
    Columns = int(input("Give the number of columns:"))  
    matrix = np.array([[int(input()) for c in range (Columns)] for r in range(Rows)])
    print(matrix)
    print("None of the elements of a given array is zero ?" ,np.all(matrix))

In [14]:
chechzeroelement()

Give the number of rows:3
Give the number of columns:3
1
2
3
4
5
6
7
8
9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [20]:
def chech_non_zero_element():
    Rows = int(input("Give the number of rows:"))  
    Columns = int(input("Give the number of columns:"))  
    matrix = np.array([[int(input()) for c in range (Columns)] for r in range(Rows)])
    print(matrix)
    print("ny of the elements of a given array is non-zero ?" ,np.any(matrix))

In [21]:
chech_non_zero_element()

Give the number of rows:3
Give the number of columns:3
0
0
0
0
0
0
0
0
0
[[0 0 0]
 [0 0 0]
 [0 0 0]]
ny of the elements of a given array is non-zero ? False


### Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [23]:
def wise_comparison():
    Rows = int(input("Give the number of rows:"))  
    Columns = int(input("Give the number of columns:"))
    print("Enter the First matrix")
    matrix1 = np.array([[int(input()) for c in range (Columns)] for r in range(Rows)])
    print("Enter the Second matrix")
    matrix2 = np.array([[int(input()) for c in range (Columns)] for r in range(Rows)])
    print("Comparison - equal:")
    print(np.equal(matrix1, matrix2))
    print("Comparison - equal within a tolerance:")
    print(np.allclose(matrix1, matrix2))

In [24]:
wise_comparison()

Give the number of rows:3
Give the number of columns:3
Enter the First matrix
1
2
3
4
5
6
7
8
9
Enter the Second matrix
1
2
3
4
5
6
7
8
1
Comparison - equal:
[[ True  True  True]
 [ True  True  True]
 [ True  True False]]
Comparison - equal within a tolerance:
False


### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [31]:
array_of10_zeros = np.zeros(10)
array_of10_ones = np.ones(10)
array_of10_fives = np.zeros(10)+5
print(f"array of 10 zeros {array_of10_zeros}\narray of 10 ones {array_of10_ones}\narray of 10 fives {array_of10_fives}")

array of 10 zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of 10 ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 10 fives [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Write a NumPy program to create an array of the integers from 30 to70.

In [33]:
array1 = np.array(range(30,70))
array1

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

### Write a NumPy program to create a 3x3 identity matrix

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Write a NumPy program to generate a random number between 0 and 1

In [65]:
np.random.normal(0,1,1)

array([-0.85083623])

### Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [66]:
np.random.normal(0,1,15)

array([-0.5785155 ,  1.27490584,  1.55790806, -2.16240971, -0.02907958,
       -1.5351298 ,  1.4029928 , -1.41887912, -1.61084318, -0.75777306,
       -0.84844043,  0.59588671,  0.75386802, -3.22365099,  0.433614  ])

### Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [80]:
print([np.arange(15,55)[1:-1]])

[array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])]


### Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [94]:
np.random.randint(0,11,5)

array([ 1,  1, 10,  0,  7])

### Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [118]:
arra1= np.zeros((10,10))
arra1[0: ,0] =1
arra1[0 ,1:] =1
arra1[1:,-1] =1
arra1[-1 ,1:] =1
arra1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [130]:
arra1= np.zeros((5,5))
arra1[0,0],arra1[1,1],arra1[2,2],arra1[3,3],arra1[4,4]=[1,2,3,4,5]
arra1

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

### Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [136]:
arra1 = np.ones((4,4))
for i in range(0,len(arra1)):
    arra1[i][i]=0
arra1[2][0]=0
arra1[3][1]=0
arra1[0][2]=0
arra1[1][3]=0
arra1

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

### Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [137]:
import numpy as np
import os
x = np.arange(10)
y = np.arange(11)
np.savez('temp_arra.npz', x=x, y=y)
print("Load arrays from the 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]


### Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number

In [152]:
def extractless(matrix,num):
    matrix =matrix[matrix<num]
    return matrix

def extractgreater(matrix,num):
    matrix =matrix[matrix>num]
    return matrix    

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
matrix = np.array([[int(input()) for c in range (Columns)] for r in range(Rows)])
num = int(input("please enter the value"))
lower = extractless(matrix,num)
print(lower)
higher = extractgreater(matrix,num)
print(higher)

Give the number of rows:3
Give the number of columns:3
1
2
3
4
5
6
7
8
9
please enter the value5
[1 2 3 4]
[6 7 8 9]
